# Generated by Django 5.2.4 on 2025-08-17 02:00
# NOTE: Manually created to synchronize the database schema with the existing model definition.

from django.db import migrations, models

class Migration(migrations.Migration):

    # Ensure this migration runs after the migration that introduced Historical models (0006)
    # This dependency name is based on the migration files provided in the initial prompt.
    dependencies = [
        # IMPORTANT: Ensure this matches the actual filename of migration 0006 in your project
        ('quiz', '0006_historicalanswer_historicalcategory_and_more.py'),
    ]

    operations = [
        # Add the status field to the main Question model
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (Admin Only)'), ('LIVE', 'Live (Visible to Users)')], default='DRAFT', help_text="Only 'Live' questions are shown to users.", max_length=5),
        ),
        # CRITICAL: Add the status field to the HistoricalQuestion model as well (for django-simple-history)
        migrations.AddField(
            model_name='historicalquestion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (Admin Only)'), ('LIVE', 'Live (Visible to Users)')], default='DRAFT', help_text="Only 'Live' questions are shown to users.", max_length=5),
        ),
    ]