# Generated by Django 5.2.4 on 2025-08-05 22:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceSJTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField(help_text='The situation presented to the candidate.')),
                ('rationale', models.TextField(help_text='Detailed explanation of the correct answers/ranking.')),
                ('is_pilot', models.BooleanField(default=False, help_text='Pilot questions are included in the exam but not scored.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SJTAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCQAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Check if this is one of the 3 best options.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_actions', to='sjt_prep.multiplechoicesjtquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RankingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField(help_text='The situation presented to the candidate.')),
                ('rationale', models.TextField(help_text='Detailed explanation of the correct answers/ranking.')),
                ('is_pilot', models.BooleanField(default=False, help_text='Pilot questions are included in the exam but not scored.')),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sjt_prep.sjtattribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='multiplechoicesjtquestion',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sjt_prep.sjtattribute'),
        ),
        migrations.CreateModel(
            name='HistoricalRankingQuestion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('scenario', models.TextField(help_text='The situation presented to the candidate.')),
                ('rationale', models.TextField(help_text='Detailed explanation of the correct answers/ranking.')),
                ('is_pilot', models.BooleanField(default=False, help_text='Pilot questions are included in the exam but not scored.')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attribute', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sjt_prep.sjtattribute')),
            ],
            options={
                'verbose_name': 'historical ranking question',
                'verbose_name_plural': 'historical ranking questions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMultipleChoiceSJTQuestion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('scenario', models.TextField(help_text='The situation presented to the candidate.')),
                ('rationale', models.TextField(help_text='Detailed explanation of the correct answers/ranking.')),
                ('is_pilot', models.BooleanField(default=False, help_text='Pilot questions are included in the exam but not scored.')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attribute', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sjt_prep.sjtattribute')),
            ],
            options={
                'verbose_name': 'historical multiple choice sjt question',
                'verbose_name_plural': 'historical multiple choice sjt questions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RankableAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.CharField(max_length=500)),
                ('correct_rank', models.PositiveSmallIntegerField(help_text='The correct rank (1=Most Appropriate, 5=Least Appropriate)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='sjt_prep.rankingquestion')),
            ],
            options={
                'ordering': ['correct_rank'],
                'unique_together': {('question', 'correct_rank')},
            },
        ),
    ]
